version: '3'
services:
  dongsoj-backend-gateway:
    container_name: dongsoj-backend-gateway
    build:
      context: ./dongsoj-backend-gateway
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    networks:
      - mynetwork
  dongsoj-backend-user-service:
    container_name: dongsoj-backend-user-service
    build:
      context: ./dongsoj-backend-user-service
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - mynetwork
    depends_on:
      - dongsoj-backend-gateway
  dongsoj-backend-question-service:
    container_name: dongsoj-backend-question-service
    build:
      context: ./dongsoj-backend-question-service
      dockerfile: Dockerfile
    ports:
      - "8103:8103"
    networks:
      - mynetwork
    depends_on:
      - dongsoj-backend-user-service
      - dongsoj-backend-gateway
  dongsoj-backend-judge-service:
    container_name: dongsoj-backend-judge-service
    build:
      context: ./dongsoj-backend-judge-service
      dockerfile: Dockerfile
    ports:
      - "8104:8104"
    networks:
      - mynetwork
    depends_on:
      - dongsoj-backend-user-service
      - dongsoj-backend-question-service
      - dongsoj-backend-gateway
networks:
  mynetwork:
