spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      routes:
        - id: dongsoj-backend-user-service
          uri: lb://dongsoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: dongsoj-backend-question-service
          uri: lb://dongsoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: dongsoj-backend-judge-service
          uri: lb://dongsoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: dongsoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
# 这个配置是不用看token是否合法 直接通过
#gateway:
#  excludedUrls: /api/user/get/login,/api/user/logout,/user/register,/api/user/update/my,/api/user/login,/user/getLoginUser,/api/user/register,/api/question/list/page/vo,/api/file
